routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Frontend Route
Route::get('/','HomeController@index');
Route::get('/productByCategory/{id}','HomeController@productByCategory')->name('category.products');
Route::get('/productByManufacture/{id}','HomeController@productByManufacture')->name('manufacture.products');
Route::get('/product/details/{id}', 'HomeController@details')->name('product.details');

//Route::post('/add-to-cart','CartController@add_to_cart');
//Route::get('/show-cart','CartController@show_cart');
Route::resource('cart','CartController');
//Backend Route
Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin-dashboard','AdminController@dashboard');
Route::get('/logout','SuperAdminController@logout');

Route::resource('category','Admin\CategoryController');
Route::get('/unactive_category/{id}','Admin\CategoryController@unactive');
Route::get('/active_category/{id}','Admin\CategoryController@active');


Route::resource('manufacture','Admin\ManufactureController');
Route::get('/unactive_manufacture/{id}','Admin\ManufactureController@unactive');
Route::get('/active_manufacture/{id}','Admin\ManufactureController@active');

Route::resource('product','Admin\ProductController');
Route::get('/unactive_product/{id}','Admin\ProductController@unactive');
Route::get('/active_product/{id}','Admin\ProductController@active');

Route::resource('slider','Admin\SliderController');
Route::get('/unactive_slider/{id}','Admin\SliderController@unactive');
Route::get('/active_slider/{id}','Admin\SliderController@active');

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = ['status','image'];

    public function scopePublished($query)
    {
        return $query->where('status', 1);
    }
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Slider;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Carbon\Carbon;
use DB;
class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::latest()->get();
        return view('admin.slider.index',compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $slider = new Slider;
        if ($request->hasFile('image')) {
            $uploadPath = public_path('/uploads/sliders');
            $extension = $request->image->getClientOriginalExtension();
            $timestamp = str_replace([' ', ':'], '--', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
            $fileName = $timestamp . '.' . $extension;
            $request->image->move($uploadPath, $fileName);
            $slider->image = $fileName;
        }else{
            $slider->image = NULL;
        }
        $slider->status = $request->status;
        $slider->save();

        Toastr::success('Slider Successfully Create :)','Success');
        return redirect(route('slider.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Slider $slider)
    {
        return view('admin.slider.show',compact('slider'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::find($id);
        return view('admin.slider.edit',compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Slider::find($id);
        if ($request->hasFile('image')) {
            $uploadPath = public_path('/uploads/sliders');
            $extension = $request->image->getClientOriginalExtension();
            $timestamp = str_replace([' ', ':'], '--', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
            $fileName = $timestamp . '.' . $extension;
            $request->image->move($uploadPath, $fileName);
            $slider->image = $fileName;
        }else{
            $slider->image = NULL;
        }
        $slider->status = $request->status;
        $slider->save();
        Toastr::success('Slider Successfully Updated :)' ,'Success');
        return redirect()->route('slider.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Slider::find($id)->delete();
        Toastr::success('Slider Successfully Deleted :)','Success');
        return redirect()->back();
    }

    public function unactive($id)
    {
        DB::table('sliders')->where('id',$id)
            ->update(['status' => 0]);
        Toastr::success('Slider Unactive Successfully  :)','Success');
        return Redirect(route('slider.index'));
    }

    public function active($id)
    {
        DB::table('sliders')
            ->where('id',$id)
            ->update(['status' => 1]);
        Toastr::success('Slider Active Successfully  :)','Success');
        return Redirect(route('slider.index'));
    }




}

resources/views/admin/slider/create.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <i class="icon-edit"></i>
            <a href="#">Add Slider</a>
        </li>
    </ul>

    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon edit"></i><span class="break"></span>Add Slider</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <form class="form-horizontal" action="{{ route('slider.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <fieldset>

                        <div class="control-group">
                            <label class="control-label" for="image">Slider Image</label>
                            <div class="controls">
                                <input type="file"  id="image" name="image">
                            </div>
                        </div>


                        <div class="control-group hidden-phone">
                            <label class="control-label" for="status">Publication Status</label>
                            <div class="controls">
                                <input type="checkbox" name="status"  value="1">
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Add Slider</button>
                            <a class="btn btn-primary pull-left" href="{{route('slider.create')}}">
                                Reset
                            </a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection

resources/views/admin/slider/edit.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <i class="icon-edit"></i>
            <a href="#">Add Slider</a>
        </li>
    </ul>

    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon edit"></i><span class="break"></span>Add Slider</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <form class="form-horizontal" action="{{ route('slider.update',$slider->id) }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <fieldset>

                        <div class="control-group">
                            <label class="control-label" for="image">Slider Image</label>
                            <div class="controls">
                                <input type="file"  id="image" name="image">
                            </div>
                        </div>


                        <div class="control-group hidden-phone">
                            <label class="control-label" for="status">Publication Status</label>
                            <div class="controls">
                                <input type="checkbox" name="status"  value="1">
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a class="btn btn-primary pull-left" href="{{route('slider.index')}}">
                                Slider
                            </a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection

resources/views/admin/slider/index.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Slider Table</a></li>
    </ul>

    <div class="row-fluid sortable">
        <a class="btn btn-info pull-right" href="{{route('slider.create')}}">
            Add Slider
        </a>
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon user"></i><span class="break"></span>Slider</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable">
                    <thead>
                    <tr>
                        <th>SL</th>

                        <th>Slider Image</th>
                        <th>status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>




                        @foreach($sliders as $slider)
                    <tr>
                        <td>{{ $loop->index + 1}}</td>
                        <td><img style="height:100px; width: 100px" src="{{asset('uploads/sliders/'.$slider->image)}}"></td>


                        <td class="center">
                            @if($slider->status==1)
                                <span class="label label-success">Active</span>

                            @else
                                <span class="label label-warning">Unactive</span>

                            @endif
                        </td>

                        <td class="center">
                            @if($slider->status==1)
                            <a class="btn btn-success" href="{{ URL::to('/unactive_slider/'.$slider->id) }}">
                                <i class="halflings-icon white thumbs-up"></i>
                            </a>
                            @else
                                <a class="btn btn-warning" href="{{ URL::to('/active_slider/'.$slider->id) }}">
                                    <i class="halflings-icon white thumbs-down"></i>
                                </a>

                            @endif
                            <a class="btn btn-info" href="{{route('slider.edit',$slider->id)}}">
                                <i class="halflings-icon white edit"></i>
                            </a>

                            </a>
                                <button class="btn btn-danger waves-effect" type="button" onclick="deleteslider({{ $slider->id }})">
                                    <i class="halflings-icon white trash"></i>
                                </button>
                                <form id="delete-form-{{ $slider->id }}" action="{{ route('slider.destroy',$slider->id) }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection
@push('js')
<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
<script type="text/javascript">
    function deleteslider(id) {
        swal({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false,
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
            event.preventDefault();
            document.getElementById('delete-form-'+id).submit();
        }else if (
                // Read more about handling dismissals
        result.dismiss === swal.DismissReason.cancel
        ) {
            swal(
                    'Cancelled',
                    'Your data is safe :)',
                    'error'
            )
        }
    })
    }
</script>
@endpush

resources/views/admin/slider/show.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Category View</a></li>
    </ul>

    <div class="row-fluid sortable">
           <h1 style="color: #0044cc"> <b>Category View</b></h1>
        <br/>
        <br/>

       <p> <b>Category Name:</b>  {{ $category->name }}</p>
       <p> <b>Category Description:</b>  {{ $category->description }}</p>
       <p> <b>Category Status:</b>  {{ $category->status}}</p>
    </div><!--/row-->


@endsection