routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Frontend Route
Route::get('/','HomeController@index');
Route::get('/productByCategory/{id}','HomeController@productByCategory')->name('category.products');
Route::get('/productByManufacture/{id}','HomeController@productByManufacture')->name('manufacture.products');
Route::get('/product/details/{id}', 'HomeController@details')->name('product.details');

//Route::post('/add-to-cart','CartController@add_to_cart');
//Route::get('/show-cart','CartController@show_cart');
Route::resource('cart','CartController');
//Backend Route
Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin-dashboard','AdminController@dashboard');
Route::get('/logout','SuperAdminController@logout');

Route::resource('category','Admin\CategoryController');
Route::get('/unactive_category/{id}','Admin\CategoryController@unactive');
Route::get('/active_category/{id}','Admin\CategoryController@active');


Route::resource('manufacture','Admin\ManufactureController');
Route::get('/unactive_manufacture/{id}','Admin\ManufactureController@unactive');
Route::get('/active_manufacture/{id}','Admin\ManufactureController@active');

Route::resource('product','Admin\ProductController');
Route::get('/unactive_product/{id}','Admin\ProductController@unactive');
Route::get('/active_product/{id}','Admin\ProductController@active');

Route::resource('slider','Admin\SliderController');
Route::get('/unactive_slider/{id}','Admin\SliderController@unactive');
Route::get('/active_slider/{id}','Admin\SliderController@active');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'description','status','image'];

    public function categories(){

        return $this->belongsToMany('App\Category')->withTimestamps();
    }

    public function manufactures(){

        return $this->belongsToMany('App\Manufacture')->withTimestamps();
    }

    public function scopePublished($query)
    {
        return $query->where('status', 1);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use App\Category;
use App\Manufacture;
use Brian2694\Toastr\Facades\Toastr;

use Carbon\Carbon;
use DB;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products= Product::latest()->get();
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categories= Category::all();
        $manufactures= Manufacture::all();
        return view('admin.product.create',compact('categories','manufactures'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $product = new Product;
        $product->name = $request->name;
        $product->short_description = $request->short_description;
        $product->long_description = $request->long_description;
        $product->price = $request->price;

        if ($request->hasFile('image')) {
            $uploadPath = public_path('/uploads/images');
            $extension = $request->image->getClientOriginalExtension();
            $timestamp = str_replace([' ', ':'], '--', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
            $fileName = $timestamp . '.' . $extension;
            $request->image->move($uploadPath, $fileName);
            $product->image = $fileName;
        }else{
            $product->image = NULL;
        }
        $product->size = $request->size;
        $product->color= $request->color;
        $product->status= $request->status;
        $product->save();

        $product->categories()->attach($request->categories);
        $product->manufactures()->attach($request->manufactures);

        Toastr::success('product Successfully Create :)','Success');
        return redirect(route('product.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $categories= Category::all();
        $manufactures= Manufacture::all();
        $product = Product::find($id);
        return view('admin.product.edit',compact('product','categories','manufactures'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        if ($request->hasFile('image')) {
            $uploadPath = public_path('/uploads/images');
            $extension = $request->image->getClientOriginalExtension();
            $timestamp = str_replace([' ', ':'], '--', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
            $fileName = $timestamp . '.' . $extension;
            $request->image->move($uploadPath, $fileName);
            $product->image = $fileName;
        }else{
            $product->image = NULL;
        }
        $product->name = $request->name;
        $product->short_description = $request->short_description;
        $product->long_description = $request->long_description;
        $product->price = $request->price;

        $product->size = $request->size;
        $product->color= $request->color;
        $product->status = $request->status;
        $product->save();

        $product->categories()->sync($request->categories);
        $product->manufactures()->sync($request->manufactures);

        Toastr::success('Product Successfully Updated :)' ,'Success');
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {


        Product::find($id)->delete();
        Toastr::success('product Successfully Deleted :)','Success');
        return redirect()->back();
    }

    public function unactive($id)
    {
        DB::table('products')->where('id',$id)
            ->update(['status' => 0]);
        Toastr::success('Product Unactive Successfully  :)','Success');
        return Redirect(route('product.index'));
    }

    public function active($id)
    {
        DB::table('products')
            ->where('id',$id)
            ->update(['status' => 1]);
        Toastr::success('Product Active Successfully  :)','Success');
        return Redirect(route('product.index'));
    }




}

resources/views/admin/product/create.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <i class="icon-edit"></i>
            <a href="#">Add Product</a>
        </li>
    </ul>

    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon edit"></i><span class="break"></span>Add Product</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <form class="form-horizontal" action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <fieldset>

                        <div class="control-group">
                            <label class="control-label" for="name">Product Name</label>
                            <div class="controls">
                                <input type="text"  id="name" name="name">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="category">Product Category</label>
                            <div class="controls">
                                <select name="categories[]" id="category" data-rel="chosen">
                                    <option>Select Category</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="category">Product Manufacture</label>
                            <div class="controls">
                                <select name="manufactures[]" id="manufacture" data-rel="chosen">
                                    <option>Select Manufacture</option>
                                    @foreach($manufactures as $manufacture)
                                        <option value="{{ $manufacture->id }}">{{ $manufacture->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="short_description">Product Short Description</label>
                            <div class="controls">
                                <textarea id="short_description" rows="3" name="short_description"></textarea>
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="long_description">Product Long Description</label>
                            <div class="controls">
                                <textarea id="long_description" rows="3" name="long_description"></textarea>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="price">Product Price</label>
                            <div class="controls">
                                <input type="text"  id="price" name="price">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="image">Product Image</label>
                            <div class="controls">
                                <input type="file"  id="image" name="image">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="size">Product Size</label>
                            <div class="controls">
                                <input type="text"  id="size" name="size">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="color">Product Color</label>
                            <div class="controls">
                                <input type="text"  id="color" name="color">
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="status">Publication Status</label>
                            <div class="controls">
                                <input type="checkbox" name="status"  value="1">
                            </div>
                        </div>

                       <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Add product</button>
                            <a class="btn btn-primary pull-left" href="{{route('product.create')}}">
                              Reset
                            </a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="/">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <i class="icon-edit"></i>
            <a href="#">Edit Product</a>
        </li>
    </ul>

    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon edit"></i><span class="break"></span>Edit Product</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <form class="form-horizontal" action="{{ route('product.update',$product->id) }}" method="POST" >
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <fieldset>

                        <div class="control-group">
                            <label class="control-label" for="name">Product Name</label>
                            <div class="controls">
                                <input type="text"  id="name" name="name" value="{{ $product->name }}">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="category">Product Category</label>
                            <div class="controls">
                                <select name="categories[]" id="category" data-rel="chosen">
                                    <option>Select Category</option>
                                    @foreach($categories as $category)
                                        <option
                                                @foreach($product->categories as $category )
                                                        {{ $category->id == $category->id ? 'selected': ''}}
                                                @endforeach
                                                value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="category">Product Manufacture</label>
                            <div class="controls">
                                <select name="manufactures[]" id="manufacture" data-rel="chosen">
                                    <option>Select Manufacture</option>
                                    @foreach($manufactures as $manufacture)
                                        <option
                                                @foreach($product->manufactures as $manufacture)
                                                {{ $manufacture->id == $manufacture->id ? 'selected': ''}}
                                                @endforeach
                                                value="{{ $manufacture->id }}">{{ $manufacture->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="short_description">Product Short Description</label>
                            <div class="controls">
                                <textarea id="short_description" rows="3" name="short_description" > {{ $product->short_description }}</textarea>
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="long_description">Product Long Description</label>
                            <div class="controls">
                                <textarea id="long_description" rows="3" name="long_description">{{ $product->long_description }}</textarea>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="price">Product Price</label>
                            <div class="controls">
                                <input type="text"  id="price" name="price"  value="{{ $product->price }}">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="image">Product Image</label>
                            <div class="controls">
                                <input type="file"  id="image" name="image">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="size">Product Size</label>
                            <div class="controls">
                                <input type="text"  id="size" name="size"  value="{{ $product->size }}">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="color">Product Color</label>
                            <div class="controls">
                                <input type="text"  id="color" name="color"  value="{{ $product->color }}">
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Update product</button>
                            <a class="btn btn-info" href="{{route('product.edit',$product->id)}}">
                                Reset
                            </a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Product Table</a></li>
    </ul>

    <div class="row-fluid sortable">
        <a class="btn btn-info pull-right" href="{{route('product.create')}}">
            Add product
        </a>

        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon user"></i><span class="break"></span>Product</h2>

                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable">
                    <thead>
                    <tr>
                        <th>SL</th>
                        <th>Product Name</th>
                        {{--<th>Product Description</th>--}}
                        <th>Image</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Brand</th>
                        <th>Status</th>
                        <th style="text-align: center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>




                        @foreach($products as $product)
                    <tr>
                        <td>{{ $loop->index + 1}}</td>
                        <td>{{ $product->name}}</td>
                        {{--<td>{{ str_limit($product->short_description,'15') }}</td>--}}
                        <td><img style="height:100px; width: 100px" src="{{asset('uploads/images/'.$product->image)}}"></td>

                        <td>{{($product->price) }}</td>
                        <td>

                            @foreach($product->categories as $category)

                                {{ $category->name }} <br/>
                            @endforeach
                        </td>
                        <td>

                            @foreach($product->manufactures as $manufacture)

                                {{ $manufacture->name }} <br/>
                            @endforeach
                        </td>

                        <td class="center">
                            @if($product->status==1)
                                <span class="label label-success">Active</span>

                            @else
                                <span class="label label-warning">Unactive</span>

                            @endif
                        </td>

                        <td class="center" style="text-align: center">
                            @if($product->status==1)
                            <a class="btn btn-success" href="{{ URL::to('/unactive_product/'.$product->id) }}">
                                <i class="halflings-icon white thumbs-up"></i>
                            </a>
                            @else
                                <a class="btn btn-warning" href="{{ URL::to('/active_product/'.$product->id) }}">
                                    <i class="halflings-icon white thumbs-down"></i>
                                </a>

                            @endif
                            <a class="btn btn-info" href="{{route('product.edit',$product->id)}}">
                                <i class="halflings-icon white edit"></i>
                            </a>

                            <a class="btn btn-primary" href="{{route('product.show',$product->id)}}">
                                <i class="halflings-icon white show"></i>
                            </a>

                            </a>
                                <button class="btn btn-danger waves-effect" type="button" onclick="deleteProduct({{ $product->id }})">
                                    <i class="halflings-icon white trash"></i>
                                </button>
                                <form id="delete-form-{{ $product->id }}" action="{{ route('product.destroy',$product->id) }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection
@push('js')
<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
<script type="text/javascript">
    function deleteProduct(id) {
        swal({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false,
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
            event.preventDefault();
            document.getElementById('delete-form-'+id).submit();
        }else if (
                // Read more about handling dismissals
        result.dismiss === swal.DismissReason.cancel
        ) {
            swal(
                    'Cancelled',
                    'Your data is safe :)',
                    'error'
            )
        }
    })
    }
</script>
@endpush

resources/views/admin/product/show.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Manufacture View</a></li>
    </ul>

    <div class="row-fluid sortable">
           <h1 style="color: #0044cc"> <b>Manufacture View</b></h1>
        <a class="btn btn-primary pull-right" href="{{route('manufacture.index')}}">
            Manufacture
        </a>
        <br/>
        <br/>

       <p> <b>manufacture Name:</b>  {{ $manufacture->name }}</p>
       <p> <b>manufacture Description:</b>  {{ $manufacture->description }}</p>
       <p> <b>manufacture Status:</b>  {{ $manufacture->status}}</p>
    </div><!--/row-->


@endsection