routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Frontend Route
Route::get('/','HomeController@index');
Route::get('/productByCategory/{id}','HomeController@productByCategory')->name('category.products');
Route::get('/productByManufacture/{id}','HomeController@productByManufacture')->name('manufacture.products');
Route::get('/product/details/{id}', 'HomeController@details')->name('product.details');

//Route::post('/add-to-cart','CartController@add_to_cart');
//Route::get('/show-cart','CartController@show_cart');
Route::resource('cart','CartController');
//Backend Route
Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin-dashboard','AdminController@dashboard');
Route::get('/logout','SuperAdminController@logout');

Route::resource('category','Admin\CategoryController');
Route::get('/unactive_category/{id}','Admin\CategoryController@unactive');
Route::get('/active_category/{id}','Admin\CategoryController@active');


Route::resource('manufacture','Admin\ManufactureController');
Route::get('/unactive_manufacture/{id}','Admin\ManufactureController@unactive');
Route::get('/active_manufacture/{id}','Admin\ManufactureController@active');

Route::resource('product','Admin\ProductController');
Route::get('/unactive_product/{id}','Admin\ProductController@unactive');
Route::get('/active_product/{id}','Admin\ProductController@active');

Route::resource('slider','Admin\SliderController');
Route::get('/unactive_slider/{id}','Admin\SliderController@unactive');
Route::get('/active_slider/{id}','Admin\SliderController@active');

app/Manufacture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manufacture extends Model
{

    public function products(){

        return $this->belongsToMany('App\Product')->withTimestamps();
    }


}

app/Http/Controllers/Admin/ManufactureController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Manufacture;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Redirect;
use DB;

class ManufactureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $manufactures= Manufacture::latest()->get();
        return view('admin.manufacture.index',compact('manufactures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.manufacture.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $manufacture = new Manufacture;
        $manufacture->name = $request->name;
        $manufacture->description = $request->description;
        $manufacture->save();
        Toastr::success('Manufacture Successfully Create :)','Success');
        return redirect(route('manufacture.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Manufacture $manufacture)
    {
        return view('admin.manufacture.show',compact('manufacture'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $manufacture = Manufacture::find($id);
        return view('admin.manufacture.edit',compact('manufacture'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $manufacture = Manufacture::find($id);
        $manufacture->name = $request->name;
        $manufacture->description = $request->description;
        $manufacture->save();
        Toastr::success('Manufacture Successfully Updated :)' ,'Success');
        return redirect()->route('manufacture.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Manufacture::find($id)->delete();
        Toastr::success('Manufacture Successfully Deleted :)','Success');
        return redirect()->back();
    }

    public function unactive($id)
    {
        DB::table('manufactures')->where('id',$id)
            ->update(['status' => 0]);
        Toastr::success('Manufacture Unactive Successfully  :)','Success');
        return Redirect(route('manufacture.index'));
    }

    public function active($id)
    {
        DB::table('manufactures')
            ->where('id',$id)
            ->update(['status' => 1]);
        Toastr::success('Manufacture Active Successfully  :)','Success');
        return Redirect(route('manufacture.index'));
    }



}

resources/views/admin/manufacture/create.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <i class="icon-edit"></i>
            <a href="#">Add Manufacture</a>
        </li>
    </ul>

    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon edit"></i><span class="break"></span>Add Manufacture</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <form class="form-horizontal" action="{{ route('manufacture.store') }}" method="POST">
                    {{ csrf_field() }}
                    <fieldset>

                        <div class="control-group">

                            <label class="control-label" for="name">Brand Name</label>


                            <div class="controls">
                                <input type="text"  id="name" name="name">
                            </div>
                        </div>

                        <div class="control-group hidden-phone">

                            <label class="control-label" for="description">Brand Description</label>

                            <div class="controls">
                                <textarea class="cleditor" id="description" rows="3" name="description"></textarea>
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="status">Publication Status</label>
                            <div class="controls">
                                <input type="checkbox" name="status"  value="1">
                            </div>
                        </div>

                       <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Add Manufacture</button>
                            <a class="btn btn-primary pull-left" href="{{route('manufacture.create')}}">
                              Reset
                            </a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection

resources/views/admin/manufacture/edit.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="/">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <i class="icon-edit"></i>
            <a href="#">Edit Manufacture</a>
        </li>
    </ul>

    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon edit"></i><span class="break"></span>Edit manufacture</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <form class="form-horizontal" action="{{ route('manufacture.update',$manufacture->id) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <fieldset>

                        <div class="control-group">
                            <label class="control-label" for="name">Manufacture Name</label>
                            <div class="controls">
                                <input type="text"  id="name" name="name" value="{{ $manufacture->name }}">
                            </div>
                        </div>

                        <div class="control-group hidden-phone">
                            <label class="control-label" for="description">Manufacture Description</label>
                            <div class="controls">
                                <textarea class="cleditor" id="description" rows="3" name="description"> {{ $manufacture->description }}</textarea>
                            </div>
                        </div>


                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Update Manufacture</button>
                            <a class="btn btn-info" href="{{route('manufacture.edit',$manufacture->id)}}">
                                Reset
                            </a>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection

resources/views/admin/manufacture/index.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Manufacture Table</a></li>
    </ul>

    <div class="row-fluid sortable">
        <a class="btn btn-info pull-right" href="{{route('manufacture.create')}}">

            Add Brand



        </a>

        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon user"></i><span class="break"></span>Members</h2>

                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable">
                    <thead>
                    <tr>
                        <th>SL</th>
                        <th>Manufacture Name</th>
                        <th>Manufacture Description</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>




                        @foreach($manufactures as $manufacture)
                    <tr>
                        <td>{{ $loop->index + 1}}</td>
                        <td>{{ $manufacture->name}}</td>
                        <td>{{ str_limit($manufacture->description,'15') }}</td>

                        <td class="center">
                            @if($manufacture->status==1)
                                <span class="label label-success">Active</span>

                            @else
                                <span class="label label-warning">Unactive</span>

                            @endif
                        </td>

                        <td class="center">
                            @if($manufacture->status==1)
                            <a class="btn btn-success" href="{{ URL::to('/unactive_manufacture/'.$manufacture->id) }}">
                                <i class="halflings-icon white thumbs-up"></i>
                            </a>
                            @else
                                <a class="btn btn-warning" href="{{ URL::to('/active_manufacture/'.$manufacture->id) }}">
                                    <i class="halflings-icon white thumbs-down"></i>
                                </a>

                            @endif
                            <a class="btn btn-info" href="{{route('manufacture.edit',$manufacture->id)}}">
                                <i class="halflings-icon white edit"></i>
                            </a>

                            <a class="btn btn-primary" href="{{route('manufacture.show',$manufacture->id)}}">
                                <i class="halflings-icon white show"></i>
                            </a>

                            </a>
                                <button class="btn btn-danger waves-effect" type="button" onclick="deletemanufacture({{ $manufacture->id }})">
                                    <i class="halflings-icon white trash"></i>
                                </button>
                                <form id="delete-form-{{ $manufacture->id }}" action="{{ route('manufacture.destroy',$manufacture->id) }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div><!--/span-->

    </div><!--/row-->


@endsection
@push('js')
<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
<script type="text/javascript">
    function deletemanufacture(id) {
        swal({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false,
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
            event.preventDefault();
            document.getElementById('delete-form-'+id).submit();
        }else if (
                // Read more about handling dismissals
        result.dismiss === swal.DismissReason.cancel
        ) {
            swal(
                    'Cancelled',
                    'Your data is safe :)',
                    'error'
            )
        }
    })
    }
</script>
@endpush

resources/views/admin/manufacture/show.blade.php
@extends('layouts.backend')
@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Manufacture View</a></li>
    </ul>

    <div class="row-fluid sortable">
           <h1 style="color: #0044cc"> <b>Manufacture View</b></h1>
        <a class="btn btn-primary pull-right" href="{{route('manufacture.index')}}">
            Manufacture
        </a>
        <br/>
        <br/>

       <p> <b>manufacture Name:</b>  {{ $manufacture->name }}</p>
       <p> <b>manufacture Description:</b>  {{ $manufacture->description }}</p>
       <p> <b>manufacture Status:</b>  {{ $manufacture->status}}</p>
    </div><!--/row-->


@endsection